# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True)),
                ('texto', models.CharField(max_length=512)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField()),
                ('archivo', models.FileField(upload_to='files/%Y')),
                ('sistematizacion', models.FileField(upload_to='sistematizacion/%Y')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('comentarios', models.ManyToManyField(blank=True, to='clase.Comentario')),
            ],
        ),
    ]
