# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='sistematizacion',
            field=models.FileField(blank=True, null=True, upload_to='sistematizacion/%Y'),
        ),
    ]
