# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0003_comentario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=1030),
        ),
    ]
